# Generated by Django 3.0.5 on 2020-07-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einstein_app', '0003_course_enrolled_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
